#!/bin/bash
# /etc/init.d/beehive-client

### BEGIN INIT INFO
# Provides:          beehive-client
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to have a beehive sensor server and posting to the web service
### END INIT INFO

DIR=/opt/beehive
DAEMON=$DIR/app.py
DAEMON_NAME=beehive-client

PYTHON=/usr/bin/python3

PIDFILE=/var/run/$DAEMON_NAME.pid
LOGFILE=/var/log/$DAEMON_NAME.log

start_service() {
	if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
		echo 'Service already running' >&2
		return 1
	fi
	echo 'Starting service...' >&2
	# We do stuff here. Figure out how to run it
	echo 'Service started.' >&2
}

stop_service() {
	if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
		echo 'Servie not running' >&2
		return 1
	fi
	echo 'Stopping service...' >&2
	kill -15 $cat "$PIDFILE") && rm -f "$PIDFILE"
	echo 'Servie stopped.' >&2
}

case "$1" in 
	start)
		echo "Starting beehive-server"
		/usr/bin/python3 /home/pi/flask/app.py
		;;
	stop)
		echo "Stopping beehive-server"
		killall 
		;;
	*)
		echo "Usage: /etc/init.d/beehive-server start|stop"
		exit 1
		;;
esac
exit 0
